USE 'service_static';

CREATE TABLE GPT_LOCATION_TYPE (
ID TINYINT(3) NOT  NULL  AUTO_INCREMENT  PRIMARY  KEY,
TYPE_NAME VARCHAR(32) NOT NULL UNIQUE);

CREATE  TABLE  GPT_LOCATION  (
ID BIGINT(20) NOT  NULL  AUTO_INCREMENT  PRIMARY  KEY,
CODE VARCHAR(20) NOT NULL,
TYPE_ID TINYINT(3) NOT NULL,
PARENT BIGINT(20),
ACTIVE BIT(1) NOT NULL,
LATITUDE DECIMAL(10.6),
LONGITUDE DECIMAL(10.6),
TIME_ZONE VARCHAR(50) NOT NULL,
FOREIGN KEY (TYPE_ID) REFERENCES GPT_LOCATION_TYPE(ID)
ON DELETE CASCADE,
UNIQUE(LATITUDE, LONGITUDE),
UNIQUE(CODE));

CREATE TABLE GPT_LANGUAGE(
ID TINYINT(3) NOT  NULL  AUTO_INCREMENT  PRIMARY  KEY,
CODE VARCHAR(2) NOT NULL UNIQUE,
NAME VARCHAR(40) NOT NULL UNIQUE);

CREATE TABLE GPT_LOCATION_NAME(
LOCATION_ID BIGINT(20) NOT NULL,
LANG_ID TINYINT(3) NOT NULL,
NAME VARCHAR(255) NOT NULL UNIQUE,
FOREIGN KEY (LOCATION_ID) REFERENCES GPT_LOCATION(ID)
ON DELETE CASCADE,
FOREIGN KEY (LANG_ID) REFERENCES GPT_LANGUAGE(ID)
ON DELETE CASCADE,
PRIMARY KEY(LOCATION_ID, LANG_ID));

CREATE TABLE GPT_HOTEL_IMAGE_TYPE (
ID TINYINT(3)NOT  NULL  AUTO_INCREMENT  PRIMARY  KEY,
TYPE_NAME VARCHAR(128) NOT NULL UNIQUE);

CREATE TABLE GPT_HOTEL (
ID BIGINT(20) NOT  NULL  AUTO_INCREMENT  PRIMARY  KEY,
CODE VARCHAR(32) NOT NULL,
CITY_ID BIGINT(20) NOT NULL,
COUNTRY_ID BIGINT(20) NOT NULL,
CATEGORY_ID ENUM('Small', 'Medium', 'Large'),
CHAIN_ID BIGINT(20),
PHONE VARCHAR(100) NOT NULL,
FAX VARCHAR(50),
URL VARCHAR(255),
CHECK_IN TIME NOT NULL,
CHECK_OUT TIME NOT NULL,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
ZIP VARCHAR(50),
LATITUDE DECIMAL(10.6) NOT NULL,
LONGITUDE DECIMAL(10.6) NOT NULL,
ACTIVE BIT(1) NOT NULL,
DEFAULT_IMAGE BIGINT(20),
CREATED DATETIME,
FOREIGN KEY (CITY_ID) REFERENCES GPT_LOCATION(ID)
ON DELETE CASCADE,
FOREIGN KEY (COUNTRY_ID) REFERENCES GPT_LOCATION(ID)
ON DELETE CASCADE,
FOREIGN KEY (DEFAULT_IMAGE) REFERENCES GPT_LOCATION(ID)
ON DELETE CASCADE,
UNIQUE(PHONE),
UNIQUE(FAX),
UNIQUE(URL),
UNIQUE(CODE));

CREATE TABLE GPT_HOTEL_IMAGES (
ID BIGINT(20) NOT  NULL  AUTO_INCREMENT PRIMARY KEY,
HOTEL_ID BIGINT(20) NOT NULL,
TYPE_ID TINYINT(3) NOT NULL,
URL VARCHAR(100) NOT NULL UNIQUE,
THUMBNAIL_URL VARCHAR(100) UNIQUE,
FOREIGN KEY (HOTEL_ID) REFERENCES GPT_HOTEL(ID)
ON DELETE CASCADE,
FOREIGN KEY (TYPE_ID) REFERENCES GPT_HOTEL_IMAGE_TYPE(ID)
ON DELETE CASCADE);

CREATE TABLE GPT_HOTEL_NAME(
HOTEL_ID BIGINT(20) NOT NULL,
LANG_ID TINYINT(3) NOT NULL,
NAME VARCHAR(500) NOT NULL,
FOREIGN KEY (HOTEL_ID) REFERENCES GPT_HOTEL(ID)
ON DELETE CASCADE,
FOREIGN KEY (LANG_ID) REFERENCES GPT_LANGUAGE(ID)
ON DELETE CASCADE,
PRIMARY KEY(HOTEL_ID, LANG_ID));

INSERT INTO GPT_LANGUAGE 
(CODE, NAME)
VALUES ('en', 'Ehglish'), ('ru', 'Russian');

INSERT INTO GPT_LOCATION_TYPE
(TYPE_NAME) VALUES ('CITY'), ('COUNTRY');

/*Belarus ID=1*/
INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, ACTIVE, TIME_ZONE)
 VALUES ('375', ( SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME LIKE 'COUNTRY'), b'1', 'GMT+3');
 /*Russia ID=2*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, ACTIVE, TIME_ZONE)
 VALUES ('7', ( SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME LIKE 'COUNTRY'), b'1', 'GMT+2-12');
 /*Egypt ID=3*/
INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, ACTIVE, TIME_ZONE)
 VALUES ('20', ( SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME LIKE 'COUNTRY'), b'1', 'GMT+2');
 /*India ID=4*/
INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, ACTIVE, TIME_ZONE)
 VALUES ('91', ( SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME LIKE 'COUNTRY'), b'1', 'GMT+5:30');

/*Belarus:Minsk*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('8-017',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	1, b'1', 53.53, 27.34, 'GMT+3');

/*Belarus:Brest*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('8-016',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	1, b'1', 52.7, 23.40, 'GMT+3');

/*Belarus:Homel*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('8-023',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	1, b'1', 52.26, 30.58, 'GMT+3'); 

/*Russia:Moskow*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('495',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	2, b'1', 55.45, 37.37, 'GMT+3');

/*Russia:Saint Petersburg*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('812',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	2, b'1', 59.57, 30.19, 'GMT+3');

/*Russia:Yakutsk*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('4112',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	2, b'1', 62.1, 129.43, 'GMT+9');

/*Egypt:Cairo*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('2',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	3, b'1', 30.3, 31.14, 'GMT+2');

/*Egypt:Alexandria*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('3',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	3, b'1', 30.13, 29.57, 'GMT+2');

/*Egypt:Luxor*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('95',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	3, b'1', 25.41, 32.38, 'GMT+2');

/*India:Mumbai*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('22',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	4, b'1', 18.58, 72.49, 'GMT+5:50');

/*India:Jaipur*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('141',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	4, b'1', 26.55, 75.52, 'GMT+5:50');

/*India:Agra*/
 INSERT INTO GPT_LOCATION
(CODE, TYPE_ID, PARENT, ACTIVE, LATITUDE, LONGITUDE, TIME_ZONE)
 VALUES ('562',
 	(SELECT ID FROM GPT_LOCATION_TYPE WHERE TYPE_NAME='CITY'),
 	4, b'1', 27.18, 78.1, 'GMT+5:50');

/*Belarus*/
INSERT INTO GPT_LOCATION_NAME 
(LOCATION_ID, LANG_ID, NAME)
VALUES
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '375'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Belarus'), 
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE'375'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Беларусь'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '8-017'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Minsk'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '8-017'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Минск'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '8-016'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Brest'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '8-016'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Брест'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '8-023'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Homel'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '8-023'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Гомель');

/*Russia*/
INSERT INTO GPT_LOCATION_NAME 
(LOCATION_ID, LANG_ID, NAME)
VALUES
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '7'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Russia'), 
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE'7'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Россия'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '495'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Moskow'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '495'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Москва'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '812'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Saint Petersburg'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '812'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Санкт-Петербург'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '4112'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Yakutsk'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '4112'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Якутск');

/*Egypt*/
INSERT INTO GPT_LOCATION_NAME 
(LOCATION_ID, LANG_ID, NAME)
VALUES
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '20'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Egypt'), 
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE'20'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Египет'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '2'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Cairo'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '2'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Каир'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '3'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Alexandria'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '3'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Александрия'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '95'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Luxor'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '95'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Луксор');

/*India*/
INSERT INTO GPT_LOCATION_NAME 
(LOCATION_ID, LANG_ID, NAME)
VALUES
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '91'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'India'), 
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE'91'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Индия'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '22'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Mumbai'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '22'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Мумбай'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '141'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Jaipur'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '141'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Джайпур'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '562'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Agra'),
((SELECT ID FROM GPT_LOCATION WHERE CODE LIKE '562'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Агра');

INSERT INTO GPT_HOTEL_IMAGE_TYPE 
(TYPE_NAME)
VALUES ('Facade'), ('Yard'), ('Room'), ('Default');

/*Belarus:Minsk:Renaissance Minsk Hotel*/
INSERT INTO GPT_HOTEL
 (CODE, CITY_ID, COUNTRY_ID, CATEGORY_ID, PHONE, FAX, URL, CHECK_IN, CHECK_OUT, EMAIL, ZIP, LATITUDE, LONGITUDE, ACTIVE,
  CREATED)
  VALUES ('375-17-309-90-90', 
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='8-017'),
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='375'),
  	'Large', '309-90-90', '375-17-309 90 91', 'http://www.marriott.com/hotels/travel/mhpbr-renaissance-minsk-hotel/', '14:00:00',
  	'12:00:00', 'none1@none.COM', '220036',
  	(SELECT LATITUDE FROM GPT_LOCATION WHERE CODE='8-017'),
  	(SELECT LONGITUDE FROM GPT_LOCATION WHERE CODE='8-017'),
	b'1', '2015-02-27 00:00:00');

INSERT INTO GPT_HOTEL_IMAGES
  (HOTEL_ID, TYPE_ID, URL)
  VALUES
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-309-90-90'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Facade'),
   'https://renaissance_minsk.com/1'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-309-90-90'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://renaissance_minsk.com/2'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-309-90-90'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://renaissance_minsk.com/3'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-309-90-90'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Default'),
   'https://renaissance_minsk.com/4');

UPDATE GPT_HOTEL SET DEFAULT_IMAGE = (SELECT ID FROM GPT_HOTEL_IMAGES WHERE
 URL = 'https://renaissance_minsk.com/4') 
 WHERE CODE = '375-17-309-90-90';

 INSERT INTO GPT_HOTEL_NAME
  (HOTEL_ID, LANG_ID, NAME)
  VALUES
  	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-309-90-90'),
  	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
  	'Renaissance Minsk Hotel'),
  	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-309-90-90'),
  	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
  	'Отель «Ренессанс Минск»');

/*Belarus:Minsk:Minsk Marriott Hotel*/
INSERT INTO GPT_HOTEL
 (CODE, CITY_ID, COUNTRY_ID, CATEGORY_ID, PHONE, FAX, URL, CHECK_IN, CHECK_OUT, EMAIL, ZIP, LATITUDE, LONGITUDE, ACTIVE,
  CREATED)
  VALUES ('8-017-279-30-00', 
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='8-017'),
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='375'),
  	'Large', '279-30-00', '375-17-279 31 00', 'https://www.marriott.com/hotels/maps/travel/mhpmc-minsk-marriott-hotel/', '14:00:00',
  	'12:00:00', 'none2@none.COM', '220020',
  	(SELECT LATITUDE FROM GPT_LOCATION WHERE CODE='8-017'),
  	(SELECT LONGITUDE FROM GPT_LOCATION WHERE CODE='8-017'),
	b'1', '2015-02-27 00:00:00');

INSERT INTO GPT_HOTEL_IMAGES
  (HOTEL_ID, TYPE_ID, URL)
  VALUES
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-017-279-30-00'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Facade'),
   'https://Marriott_minsk.com/1'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-017-279-30-00'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Default'),
   'https://Marriott_minsk.com/4');

UPDATE GPT_HOTEL SET DEFAULT_IMAGE = (SELECT ID FROM GPT_HOTEL_IMAGES WHERE
 URL = 'https://Marriott_minsk.com/4') 
 WHERE CODE = '8-017-279-30-00';

 INSERT INTO GPT_HOTEL_NAME
  (HOTEL_ID, LANG_ID, NAME)
  VALUES
  	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-017-279-30-00'),
  	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
  	'Minsk Marriott Hotel'),
  	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-017-279-30-00'),
  	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
  	'Отель "Минск Марриотт"');

/*Belarus:Minsk:Hampton by Hilton Minsk City Centre*/
INSERT INTO GPT_HOTEL
 (CODE, CITY_ID, COUNTRY_ID, CATEGORY_ID, PHONE, FAX, URL, CHECK_IN, CHECK_OUT, EMAIL, ZIP, LATITUDE, LONGITUDE, ACTIVE,
  CREATED)
  VALUES ('375-17-215 40 00', 
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='8-017'),
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='375'),
  	'Large', '215 40 00', '375-17-215 40 01', 'http://hamptoninn3.hilton.com/en/hotels/belarus/hampton-by-hilton-minsk-city-centre-MSQHXHX/index.html',
  	'14:00:00', '00:00:00', 'none3@none.COM', '	220007',
  	(SELECT LATITUDE FROM GPT_LOCATION WHERE CODE='8-017'),
  	(SELECT LONGITUDE FROM GPT_LOCATION WHERE CODE='8-017'),
	b'1', '2015-02-27 00:00:00');

INSERT INTO GPT_HOTEL_IMAGES
  (HOTEL_ID, TYPE_ID, URL)
  VALUES
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-215 40 00'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Facade'),
   'https://Hampton_minsk.com/1'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-215 40 00'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Hampton_minsk.com/3'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-215 40 00'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Hampton_minsk.com/2'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-215 40 00'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Default'),
   'https://Hampton_minsk.com/4');

UPDATE GPT_HOTEL SET DEFAULT_IMAGE = (SELECT ID FROM GPT_HOTEL_IMAGES WHERE
 URL = 'https://Hampton_minsk.com/4') 
 WHERE CODE = '375-17-215 40 00';

 INSERT INTO GPT_HOTEL_NAME
  (HOTEL_ID, LANG_ID, NAME)
  VALUES
  	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-215 40 00'),
  	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
  	'Hampton by Hilton Minsk City Centre'),
  	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375-17-215 40 00'),
  	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
  	'Хемптон от Хилтон в центре Минска');

/*Belarus:Brest:"Vesta" Hotel in Brest*/
INSERT INTO GPT_HOTEL
 (CODE, CITY_ID, COUNTRY_ID, CATEGORY_ID, PHONE, FAX, URL, CHECK_IN, CHECK_OUT, EMAIL, ZIP, LATITUDE, LONGITUDE, ACTIVE,
  CREATED)
  VALUES ('375(162)20-75-33', 
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='8-016'),
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='375'),
  	'Large', '20-75-33', '375(162)20-75-41', 'http://www.hotelvesta.by/',
  	'14:00:00', '00:00:00', 'hotelvesta@tut.by', '	224005',
  	(SELECT LATITUDE FROM GPT_LOCATION WHERE CODE='8-016'),
  	(SELECT LONGITUDE FROM GPT_LOCATION WHERE CODE='8-016'),
	b'1', '2012-01-01 00:00:00');

INSERT INTO GPT_HOTEL_IMAGES
  (HOTEL_ID, TYPE_ID, URL)
  VALUES
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)20-75-33'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Facade'),
   'https://Vesta_brest.com/1'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)20-75-33'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Vesta_brest.com/3'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)20-75-33'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Vesta_brest.com/2'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)20-75-33'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Default'),
   'https://Vesta_brest.com/4');

UPDATE GPT_HOTEL SET DEFAULT_IMAGE = (SELECT ID FROM GPT_HOTEL_IMAGES WHERE
 URL = 'https://Vesta_brest.com/4') 
 WHERE CODE = '375(162)20-75-33';

INSERT INTO GPT_HOTEL_NAME
(HOTEL_ID, LANG_ID, NAME)
VALUES
	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)20-75-33'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'"Vesta" Hotel in Brest'),
	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)20-75-33'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Гостиница «Веста» в Бресте');

/*Belarus:Brest:Hermitage Hotel in Brest*/
INSERT INTO GPT_HOTEL
 (CODE, CITY_ID, COUNTRY_ID, CATEGORY_ID, PHONE, FAX, URL, CHECK_IN, CHECK_OUT, EMAIL, ZIP, LATITUDE, LONGITUDE, ACTIVE,
  CREATED)
  VALUES ('375(162)276-000', 
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='8-016'),
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='375'),
  	'Large', '276-000', '375(162)276-000', 'http://hermitagehotel.by/ru/',
  	'14:00:00', '00:00:00', 'hotel@hermitagehotel.by', '224005',
  	(SELECT LATITUDE FROM GPT_LOCATION WHERE CODE='8-016'),
  	(SELECT LONGITUDE FROM GPT_LOCATION WHERE CODE='8-016'),
	b'1', '2017-01-01 00:00:00');

INSERT INTO GPT_HOTEL_IMAGES
  (HOTEL_ID, TYPE_ID, URL)
  VALUES
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)276-000'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Facade'),
   'https://Hermitage_brest.com/1'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)276-000'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Hermitage_brest.com/3'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)276-000'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Hermitage_brest.com/2'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)276-000'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Default'),
   'https://Hermitage_b.com/4');

INSERT INTO GPT_HOTEL_NAME
(HOTEL_ID, LANG_ID, NAME)
VALUES
	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)276-000'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Hermitage Hotel in Brest'),
	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '375(162)276-000'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'Гостиница «Эрмитаж» в Бресте');

/*Belarus:Homel:Amaks visit-hotel in Homel*/
INSERT INTO GPT_HOTEL
 (CODE, CITY_ID, COUNTRY_ID, CATEGORY_ID, PHONE, FAX, URL, CHECK_IN, CHECK_OUT, EMAIL, ZIP, LATITUDE, LONGITUDE, ACTIVE,
  CREATED)
  VALUES ('8-800-555-52-25', 
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='8-023'),
  	(SELECT ID FROM GPT_LOCATION WHERE CODE='375'),
  	'Large', '555-52-25', '8-800-555-52-25', 'http://gomel.amaks-hotels.ru/',
  	'12:00:00', '12:00:00', 'gomel@amaks-hotels.ru', '246017',
  	(SELECT LATITUDE FROM GPT_LOCATION WHERE CODE='8-023'),
  	(SELECT LONGITUDE FROM GPT_LOCATION WHERE CODE='8-023'),
	b'1', '2014-01-01 00:00:00');

INSERT INTO GPT_HOTEL_IMAGES
  (HOTEL_ID, TYPE_ID, URL)
  VALUES
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-800-555-52-25'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Facade'),
   'https://Amaks_homel.com/1'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-800-555-52-25'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Amaks_homel.com/3'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-800-555-52-25'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Room'),
   'https://Amaks_homel.com/2'),
  ((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-800-555-52-25'),
   (SELECT ID FROM GPT_HOTEL_IMAGE_TYPE WHERE TYPE_NAME LIKE 'Default'),
   'https://Amaks_homel.com/4');

INSERT INTO GPT_HOTEL_NAME
(HOTEL_ID, LANG_ID, NAME)
VALUES
	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-800-555-52-25'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'en'),
	'Amaks visit-hotel in Homel'),
	((SELECT ID FROM GPT_HOTEL WHERE CODE LIKE '8-800-555-52-25'),
	(SELECT ID FROM GPT_LANGUAGE WHERE CODE LIKE 'ru'),
	'«AMAKC Визит-отель» в г. Гомеле');




